---
title: "Electoral districts and parlamentary groups"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
library(ggsflabel)
```

```{r data, include=FALSE}
raw_data_districts <- readRDS("plot_data/districts.rds")
district_choices <- unique(raw_data_districts$electoral_district) %>% stringi::stri_sort(locale = "fi_FI")

raw_data_groups <- readRDS("plot_data/parl_groups.rds")
group_choices <- unique(raw_data_groups$party) %>% stringi::stri_sort(local = "fi_FI")

```


# Static plots

## Municipality mentions by electoral district and year

```{r lineplot_districts, echo=FALSE}
lineplot_districts_data <- raw_data_districts %>%
  select(-geom)  %>%
  group_by(period, year, electoral_district) %>%
  summarise(speaker_district_count = sum(speaker_district_count, na.rm = TRUE),
            .groups = "drop") %>%
  filter((period == "1986-1995" & year <= 1995)|(period == "2004-2013" & year >= 2003)) %>%
  tibble()

lineplot_districts <- ggplot(lineplot_districts_data, aes(x = year, y = speaker_district_count, col = electoral_district))  +
  geom_line() +
  labs(x= "", y= "", title = "Mentions by electoral district") +
  theme_bw() +
  theme(legend.position = "right") +
  facet_wrap(~period, scales = "free_x")

lineplot_districts
```

## Municipality mentions by parliamentary group and year


```{r lineplot_group}
lineplot_groups_data <- raw_data_groups %>%
  select(-geom)  %>%
  group_by(period, year, party) %>%
  summarise(speaker_party_count = sum(speaker_party_count, na.rm = TRUE),
            .groups = "drop") %>%
  filter((period == "1986-1995" & year <= 1995)|(period == "2004-2013" & year >= 2003)) %>%
  tibble()

lineplot_groups <- ggplot(lineplot_groups_data, aes(x = year, y = speaker_party_count, col = party))  +
  geom_line() +
  labs(x= "", y= "", title = "Mentions by parliamentary group") +
  theme_bw() +
  theme(legend.position = "right") + 
  facet_wrap(~period, scales = "free_x")

lineplot_groups
```



## MPs mentioning regions in their own electoral disctric

```{r lineplot_mp_districts, echo = FALSE, warning=FALSE, eval = TRUE}
lineplot_mp_districts_data <- raw_data_districts %>%
  tibble() %>%
  filter(speaker_electoral_district == electoral_district) %>%
  select(-geom)  %>%
  group_by(period, year, speaker_electoral_district) %>%
  summarise(speaker_district_count = sum(speaker_district_count, na.rm = TRUE),
            speaker_district_total = sum(speaker_district_total, na.rm = TRUE), 
            .groups = "drop") %>%
  filter((period == "1986-1995" & year <= 1995)|(period == "2004-2013" & year >= 2003)) %>%
  mutate(speaker_district_prop = speaker_district_count / speaker_district_total) 

line1 <- ggplot(lineplot_mp_districts_data %>%  filter(period == "1986-1995"), aes(x = year, y = speaker_district_prop, col = speaker_electoral_district))  +
  geom_line() +
  labs(x= "", y= "", subtitle = "1986-1995") +
  scale_x_continuous(breaks= scales::pretty_breaks(), limits = c(1986,1995)) +
  theme_bw() +
  theme(legend.position = "none") +
  facet_wrap(~speaker_electoral_district)

line2 <- ggplot(lineplot_mp_districts_data %>%  filter(period == "2004-2013"), aes(x = year, y = speaker_district_prop, col = speaker_electoral_district))  +
  geom_line() +
  labs(x= "", y= "", subtitle = "2004-2013") +
  scale_x_continuous(breaks= scales::pretty_breaks(), limits = c(2004,2013)) +
  theme_bw() +
  theme(legend.position = "none") +
  facet_wrap(~speaker_electoral_district)

ggarrange(line1, line2, ncol=1, nrow=2, common.legend = FALSE)
#patchwork::wrap_plots(list(line1, line2), ncol = 1)
```



# Interactive plots

```{r plot_data_aggregate_funs, include=FALSE}

preprocess_district_data <- function(df, time_period, cut, district){
  df %>%
    filter(period == time_period) %>%
    filter(speaker_electoral_district == district) %>%
    mutate(time = ifelse(year < cut, 
                         paste(unlist(strsplit(time_period, "-"))[1], "-", (cut-1)), 
                         paste(cut, "-", unlist(strsplit(time_period, "-"))[2]))) %>%
    group_by(electoral_district, speaker_electoral_district, time) %>%
    summarize(speaker_district_count = sum(speaker_district_count, na.rm = TRUE),
              speaker_district_total = sum(speaker_district_total, na.rm = TRUE), .groups = "drop") %>%
    mutate(speaker_district_prop  = speaker_district_count / speaker_district_total) %>%
    sf::st_as_sf()
  
}

preprocess_group_data <- function(df, time_period, cut, group){
  df %>%
    filter(period == time_period) %>%
    filter(party == group) %>%
    mutate(time = ifelse(year < cut, 
                         paste(unlist(strsplit(time_period, "-"))[1], "-", (cut-1)), 
                         paste(cut, "-", unlist(strsplit(time_period, "-"))[2]))) %>%
    group_by(electoral_district, party, time) %>%
    summarize(speaker_party_count = sum(speaker_party_count, na.rm = TRUE),
              speaker_party_total = sum(speaker_party_total, na.rm = TRUE), .groups = "drop") %>%
    mutate(speaker_party_prop  = speaker_party_count / speaker_party_total) %>%
    sf::st_as_sf()
  
}
```


```{r plot_fun, include=FALSE}
plot_map <- function(df,fill = "speaker_district_count", wrap_col = "time", title = NULL, subtitle = NULL, limits = c(0,0.75)){
  
  plot <- ggplot(df,
                 aes_string(fill = fill,
                            geometry = "geom")) +
    geom_sf(colour = alpha("white", 1/3)) +
    labs(title = title, subtitle = subtitle) +
    # geom_sf_label_repel(
    #   aes(label = electoral_district, geometry = geom),
    #   fill = "grey",
    #   force = 100, nudge_x = -2, seed = 10) +
    theme_minimal() +
    theme(legend.position= "right",
          axis.text = element_blank(),
          axis.title = element_blank(),
          panel.grid = element_blank(),
          strip.text = element_text(size = 18)
    ) +
    facet_wrap(as.formula(paste("~", wrap_col))) +
    viridis::scale_fill_viridis(name = "Mentions", limits = limits)
  
  
  return(plot)
}
```


## Mentions of municipalities by MPs aggregated by MP's electoral district 

```{r mp_districts_input, echo=FALSE}
selectInput(
  'district', 
  label = 'Show mentions by MP from this electoral district:',
  choices = district_choices, 
  selected = district_choices[1]
)

```


```{r mp_districts_app, echo=FALSE, eval=TRUE}

plot_districts1 <- reactive({
  raw_data_districts %>%
    preprocess_district_data(time_period = "1986-1995", cut = 1990, district = input$district)
  
})


plot_districts2 <- reactive({
  raw_data_districts %>%
    preprocess_district_data(time_period = "2004-2013", cut = 2008, district = input$district)
  
})

p1 <- reactive({plot_districts1() %>% 
    plot_map(fill = "speaker_district_prop", title = paste("First year of the economic crisis:", 1990))
})

p2 <- reactive({plot_districts2() %>% 
    plot_map(fill = "speaker_district_prop", title = paste("First year of the economic crisis:", 2008))
})

renderPlot(
  ggarrange(p1(), p2(), ncol=1, nrow=2, common.legend = FALSE) %>%
    annotate_figure(top = text_grob(input$district, size = 24, face = "bold")),
  height = 1000
)

```


## Mentions of municipalities by MPs aggregated by parliamentary group

```{r mp_groups_input, echo = FALSE}
selectInput(
  'party', 
  label = 'Show mentions by MP from this parliamentary group:',
  choices = group_choices, 
  selected = group_choices[1]
)
```



```{r mp_groups_app, echo=FALSE, eval=TRUE}

plot_groups1 <- reactive({
  raw_data_groups %>%
    preprocess_group_data(time_period = "1986-1995", cut = 1990, group = input$party)
  
})


plot_groups2 <- reactive({
  raw_data_groups %>%
    preprocess_group_data(time_period = "2004-2013", cut = 2008, group = input$party)
  
})

p3 <- reactive({plot_groups1() %>% 
    plot_map(fill = "speaker_party_prop", title = paste("First year of the economic crisis:", 1990))
})

p4 <- reactive({plot_groups2() %>% 
    plot_map(fill = "speaker_party_prop", title = paste("First year of the economic crisis:", 2008))
})

renderPlot(
  ggarrange(p3(), p4(), ncol=1, nrow=2, common.legend = FALSE) %>%
    annotate_figure(top = text_grob(input$party, size = 24, face = "bold")),
  height = 1000
)

```

