```{r pkgs, include=FALSE}
library(tidyverse)
library(ggpubr)
library(ggsflabel)
```

```{r data, include=FALSE}
raw_data_districts <- readRDS("plot_data/districts.rds")
district_choices <- unique(raw_data_districts$electoral_district) %>% stringi::stri_sort(locale = "fi_FI")

raw_data_groups <- readRDS("plot_data/parl_groups.rds")
group_choices <- unique(raw_data_groups$party) %>% stringi::stri_sort(local = "fi_FI")

```

```{r helpers, include = FALSE}
break_labs <- function(x, n =20){
  sapply(strwrap(x, n, simplify=FALSE), paste, collapse="\n" )
}
```


## Data and obervations

### Municipality mentions by electoral district and year

```{r lineplot_districts, echo=FALSE, fig.cap = "Figure 1"}
lineplot_districts_data <- raw_data_districts %>%
  select(-geom)  %>%
  group_by(period, year, electoral_district) %>%
  summarise(speaker_district_count = sum(speaker_district_count, na.rm = TRUE),
            .groups = "drop") %>%
  filter((period == "1986-1995" & year <= 1995)|(period == "2004-2013" & year >= 2003)) %>%
  mutate(time = ifelse(period == "1986-1995", year - 1991, year - 2008)) %>%
  mutate(electoral_district = break_labs(electoral_district)) %>%
  tibble()

lineplot_districts <- ggplot(lineplot_districts_data, aes(x = time, y = speaker_district_count, col = period))  +
  geom_line() +
  labs(x= expression(t[i]), y= "", title = "Mentions by electoral district") +
  scale_x_continuous(breaks= scales::pretty_breaks(10), limits  = c(-5,5)) +
  scale_color_discrete(name="Time period",
                       breaks=c("1986-1995", "2004-2013"),
                       labels=c(expression(paste("1986-1995 (",t[0], "=1991)", sep = "")), expression(paste("2004-2013 (",t[0], "=2008)", sep = "")))) +
  theme_bw() +
  theme(legend.position = "top") +
  facet_wrap(~electoral_district)

lineplot_districts
```


### Municipality mentions by parliamentary group and year


```{r lineplot_group, echo = FALSE, fig.cap = "Figure 2"}
lineplot_groups_data <- raw_data_groups %>%
  select(-geom)  %>%
  group_by(period, year, party) %>%
  summarise(speaker_party_count = sum(speaker_party_count, na.rm = TRUE),
            .groups = "drop") %>%
  filter((period == "1986-1995" & year <= 1995)|(period == "2004-2013" & year >= 2003)) %>%
  mutate(time = ifelse(period == "1986-1995", year - 1991, year - 2008)) %>%
  mutate(party = break_labs(party)) %>%
  tibble()

lineplot_groups <- ggplot(lineplot_groups_data, aes(x = time, y = speaker_party_count, col = period))  +
  geom_line() +
  labs(x= expression(t[i]), y= "", title = "Mentions by parliamentary group", col = "") +
  scale_x_continuous(breaks= scales::pretty_breaks(10), limits  = c(-5,5)) +
  scale_color_discrete(name="Time period",
                       breaks=c("1986-1995", "2004-2013"),
                       labels=c(expression(paste("1986-1995 (",t[0], "=1991)", sep = "")), expression(paste("2004-2013 (",t[0], "=2008)", sep = "")))) +
  theme_bw() +
  theme(legend.position = "top") + 
  facet_wrap(~party)

lineplot_groups
```



### MPs mentioning regions in their own electoral disctric

```{r lineplot_mp_districts, echo = FALSE, warning=FALSE, eval = TRUE, fig.cap = "Figure 3"}
lineplot_mp_districts_data <- raw_data_districts %>%
  tibble() %>%
  select(-geom)  %>%
  filter(speaker_electoral_district == electoral_district) %>%
  group_by(period, year, speaker_electoral_district) %>%
  summarise(speaker_district_count = sum(speaker_district_count, na.rm = TRUE),
            speaker_district_total = sum(speaker_district_total, na.rm = TRUE), 
            .groups = "drop") %>%
  filter((period == "1986-1995" & year <= 1995)|(period == "2004-2013" & year >= 2003)) %>%
  mutate(time = ifelse(period == "1986-1995", year - 1991, year - 2008)) %>%
  mutate(speaker_district_prop = speaker_district_count / speaker_district_total) %>%
  mutate(speaker_electoral_district = break_labs(speaker_electoral_district))


mp_districts_line <- ggplot(lineplot_mp_districts_data, aes(x = time, y = speaker_district_prop, col = period))  +
  geom_line() +
  labs(x= expression(t[i]), y= "") +
  scale_x_continuous(breaks= scales::pretty_breaks(10), limits  = c(-5,5)) +
  scale_color_discrete(name="Time period",
                       breaks=c("1986-1995", "2004-2013"),
                       labels=c(expression(paste("1986-1995 (",t[0], "=1991)", sep = "")), expression(paste("2004-2013 (",t[0], "=2008)", sep = "")))) +
  theme_bw() +
  theme(legend.position = "top") +
  facet_wrap(~speaker_electoral_district)

mp_districts_line

# line1 <- ggplot(lineplot_mp_districts_data %>%  filter(period == "1986-1995"), aes(x = year, y = speaker_district_prop, col = speaker_electoral_district))  +
#   geom_line() +
#   labs(x= "", y= "", subtitle = "1986-1995") +
#   scale_x_continuous(breaks= scales::pretty_breaks(), limits = c(1986,1995)) +
#   theme_bw() +
#   theme(legend.position = "none") +
#   facet_wrap(~speaker_electoral_district)
# 
# line2 <- ggplot(lineplot_mp_districts_data %>%  filter(period == "2004-2013"), aes(x = year, y = speaker_district_prop, col = speaker_electoral_district))  +
#   geom_line() +
#   labs(x= "", y= "", subtitle = "2004-2013") +
#   scale_x_continuous(breaks= scales::pretty_breaks(), limits = c(2004,2013)) +
#   theme_bw() +
#   theme(legend.position = "none") +
#   facet_wrap(~speaker_electoral_district)

#patchwork::wrap_plots(list(line1, line2), ncol = 1)
```
